### ISSUE TITLE
Please provide some tutorial or sample with Laravel 8

### ISSUE THREAD

**Issue by pkd2989** [PlatformCommunity/flysystem-bunnycdn#18]
Hi, 

I tried with Laravel 8. After creating the $filesystem, when using listFiles etc. It gives me error as
Call to undefined method League\Flysystem\Filesystem::listFiles

Thanks

**Comment by pkd2989** [comment]
Never mind, got it.

The parameter 'key' is actually the password, and not the API key from Account.
Thanks

**Comment by pkd2989** [comment]
It seems I need some more info on how to use this.
- listFiles still doesnt work
- listContents works.

Also, when trying to use "put", it shows authorization error. So, what more credentials are required for this. And how to correctly send the request from Laravel.

Thanks..

**Comment by sifex** [comment]
Hi @pkd2989, please read the Laravel first-party documentation on creating custom filesystems.

https://laravel.com/docs/8.x/filesystem#custom-filesystems

You can follow the guide on my blog for setting up for Laravel 9, which will be exactly the same, but for the `AppServiceProvider.php` portion of the blog post, replace the section with the following:

```php
Storage::extend('bunnycdn', function ($app, $config) {
    $adapter = new BunnyCDNAdapter(
        new BunnyCDNClient(
            $config['storage_zone'],
            $config['api_key'],
            $config['region']
        ),
        'http://testing.b-cdn.net' # Optional
    );


    return new Filesystem($adapter, $config);
});
```
 
_Note: You're returning `new Filesystem($adapter, $config);` instead of `new FilesystemAdapter(new Filesystem($adapter, $config), $adapter, $config);`_

**Comment by sifex** [comment]
> Never mind, got it.
> 
> The parameter 'key' is actually the password, and not the API key from Account. Thanks

Also please never use your password in place of the API key...

**Comment by pkd2989** [comment]
From the BunnyCDN.PHP.Storage
https://github.com/BunnyWay/BunnyCDN.PHP.Storage

The BunnyCDNStorage constructor takes the following parameters:

-     storageZoneName - The name of your storage zone
-     apiAccessKey - The API access key (**password**)
-     storageZoneRegion - The storage zone region code (de, ny, or sg)

When I tried API key it didn't work, may be I need to check it again.
